# this part should be common and maintained in another repo
include:
  - project: lbb/devops-jobs
    file: devops.gitlab-ci.yml

# this should be the local file
python-tests:
  extends: .devops::test
  after_script:
    # fix for coverage test not read by sonar
    - sed -i 's/\/labonneboite\_common/\.\/labonneboite\_common/g' testResults/coverage.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - importer/**/*
        - pyproject.toml
    - if: ( $CI_COMMIT_BRANCH == "main" &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - importer/**/*
        - pyproject.toml

sonarqube:
  extends: .devops::sonarqube
  needs:
    - job: python-tests
  rules:
    - if: ( $CI_COMMIT_BRANCH == "main"  &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - importer/**/*
        - pyproject.toml
