name: deployment
on:
  push:
    branches:
      - main
      - refacto/PELBB-411/migrate-importer-in-airflow
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: bash .execute.sh deploy "" "$IP" "$ENV"
