name: deployment
on:
  push:
    branches:
      - main
      - refacto/PELBB-411/migrate-importer-in-airflow
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install deps
        run: sudo apt-get install -y openvpn

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy
        run: |
          bash .execute.sh connect_openvpn "$VPN_CONFIG"
          bash .execute.sh deploy "$IP" "" "$ENV" "$GITHUB_SHA"
        env:
          IP: ${{ secrets.IP }}
          ENV: ${{ secrets.ENV }}
          VPN_CONFIG: ${{ secrets.VPN_CONFIG }}
